apiVersion: v1
kind: ConfigMap
metadata:
  namespace: system-auth
  name: hydra-config
  labels:
    component: hydra
data:
  hydra.yaml: |
    dsn: postgres://postgres:password@postgres.system-auth.svc.cluster.local:5432/hydra_browser?sslmode=disable

    serve:
      public:
        port: 4444
      admin:
        port: 4445
    
    secrets:
      system:
        - DgCPtr3IlG0KFMBqHA7LQ4ixMSRqNHrA

    urls:
      self:
        issuer: http://localhost:8080/
        public: http://localhost:8080/
      login: http://localhost:8080/.auth/select-tenant/
      consent: http://localhost:8080/.auth/consent/

    ttl:
        login_consent_request: 1h
        access_token: 1h
        refresh_token: 720h
        id_token: 1h
        auth_code: 1h

    log:
      level: debug
      format: text

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system-auth
  name: hydra
  labels:
    system: auth

spec:
  replicas: 1
  selector:
    matchLabels:
      system: auth
      component: hydra

  template:
    metadata:
      labels:
        system: auth
        component: hydra
    spec:
      initContainers:
      - name: hydra-init
        image: oryd/hydra:v1.8.5
        args:
        - "--config"
        - "/etc/hydra/config/hydra.yaml"
        - "migrate"
        - "sql"
        - "-e"
        - "--yes"
        volumeMounts:
        - name: config
          mountPath: /etc/hydra/config
      containers:
      - name: hydra
        image: oryd/hydra:v1.8.5
        args:
        - "--config"
        - "/etc/hydra/config/hydra.yaml"
        - "serve"
        - "all"
        - "--dangerous-force-http"
        volumeMounts:
        - name: config
          mountPath: /etc/hydra/config
        ports:
        - name: public
          containerPort: 4444
        - name: admin
          containerPort: 4445
      volumes:
      - name: config
        configMap:
          name: hydra-config

---

apiVersion: v1
kind: Service
metadata:
  name: hydra
  namespace: system-auth
spec:
  selector:
    system: auth
    component: hydra
  ports:
  - port: 80
    targetPort: public
    name: http
  - port: 4445
    targetPort: admin
    name: admin

---

apiVersion: v1
kind: Service
metadata:
  name: hydra-admin-external
  namespace: system-auth
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    system: auth
    component: hydra
  ports:
    - name: http
      port: 4445
      targetPort: admin

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: system-auth
  name: hydra
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: hydra
          servicePort: public
      - path: /.well-known
        backend:
          serviceName: hydra
          servicePort: 80
