apiVersion: v1
kind: ConfigMap
metadata:
  namespace: system-auth
  name: local-oidc-provider
data:
  config.json: |
    {
      "idp_name": "http://local-oidc-provider:9090/",
      "port": 9090,
      "client_config": [
        {
          "client_id": "foo",
          "client_secret": "bar",
          "redirect_uris": [
            "http://studio.localhost:8080/.auth/self-service/methods/oidc/callback/sample"
          ]
        }
      ],
      "claim_mapping": {
        "openid": [ "sub" ],
        "email": [ "email", "email_verified" ],
        "profile": [ "name", "nickname" ]
      }
    }

  users.json: |
    [
      {
        "id": "SIMPLE_OIDC_USER_HARLEY",
        "email": "do@do.do",
        "email_verified": true,
        "name": "Harley Kiffe",
        "nickname": "harley",
        "password": "password",
        "groups": ["Everyone", "Sales"]
      }
    ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system-auth
  name: local-oidc-provider
spec:
  selector:
    matchLabels:
      system: auth
      component: local-oidc-provider
  template:
    metadata:
      labels:
        system: auth
        component: local-oidc-provider
    spec:
      containers:
      - name: oidc-provider
        image: qlik/simple-oidc-provider
        env:
        - name: CONFIG_FILE
          value: /etc/simple-oidc-provider/config/config.json
        - name: USERS_FILE
          value: /etc/simple-oidc-provider/config/users.json
        volumeMounts:
        - name: config
          mountPath: /etc/simple-oidc-provider/config
        ports:
        - name: http
          containerPort: 9090
      volumes:
      - name: config
        configMap:
          name: local-oidc-provider

---
apiVersion: v1
kind: Service
metadata:
  name: local-oidc-provider
  namespace: system-auth
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    system: auth
    component: local-oidc-provider
  ports:
    - name: http
      port: 9090
      targetPort: http
