---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: system-auth
  name: developer
  labels:
    tenant: Dolittle
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions"]
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - watch
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: system-auth
  name: developer
  labels:
    tenant: Dolittle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
  - kind: Group
    name: giga-tenant
    apiGroup: rbac.authorization.k8s.io
