apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: system-auth
  name: apiserver-proxy

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonator
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiserver-proxy-impersonator
subjects:
- kind: ServiceAccount
  name: apiserver-proxy
  namespace: system-auth
roleRef:
  kind: ClusterRole
  name: impersonator
  apiGroup: rbac.authorization.k8s.io
