apiVersion: v1
kind: ConfigMap
metadata:
  namespace: system-auth
  name: users
data:
  kratos.yaml: |
    dsn: postgres://postgres:password@postgresql.system-auth.svc.cluster.local:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

    serve:
      public:
        port: 4433
        base_url: http://studio.localhost:8080/.auth/
      admin:
        port: 4434

    identity:
      default_schema_url: file:///etc/kratos/config/identity.schema.json

    selfservice:
      default_browser_return_url: http://studio.localhost:8080/

      whitelisted_return_urls:
        - http://studio.localhost:8080/.auth/self-service/tenant/browser
        - /.auth/self-service/tenant/browser

      flows:
        login:
          ui_url: http://studio.localhost:8080/.auth/select-provider
          after:
            oidc:
              default_browser_return_url: /.auth/self-service/tenant/browser
              hooks:
                - hook: revoke_active_sessions

        registration:
          after:
            oidc:
              default_browser_return_url: /.auth/cookies/initiate
              hooks:
                - hook: session

        verification:
          enabled: false
        
        error:
          ui_url: http://studio.localhost:8080/.auth/error

      methods:
        profile:
          enabled: false
        link:
          enabled: false
        password:
          enabled: false
        oidc:
          enabled: true
          config:
            providers:
              - id: sample
                provider: generic
                client_id: foo
                client_secret: bar
                issuer_url: http://local-oidc-provider:9090/
                mapper_url: file:///etc/kratos/config/sample.mapper.jsonnet
                scope:
                  - profile
                  - email
                requested_claims:
                  userinfo:
                    email:
                      essential: true

    hashers:
      argon2:
        parallelism: 1
        memory: 131072
        iterations: 2
        salt_length: 16
        key_length: 16

    secrets:
      default:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE-DUH
      cookie:
        - PLEASE-CHANGE-ME-I-AM-EVEN-MORE-INSECURE-I-WAS-NEVER-LOVED

    session:
      cookie:
        persistent: true
        same_site: Lax
      lifespan: 24h

    courier:
      smtp:
        connection_uri: "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true"

    log:
      level: debug
      format: text

  identity.schema.json: |
    {
      "$id": "https://dolittle.studio/authentication/schemas/v1/customer.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Customer",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail"
            },
            "tenants": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "title": "Tenants"
            }
          },
          "required": [
            "email",
            "tenants"
          ],
          "additionalProperties": false
        }
      }
    }

  sample.mapper.jsonnet: |
    local claims = std.extVar('claims');

    {
      identity: {
        traits: {
          email: claims.email,
          tenants: []
        }
      }
    }
  
  login.yaml: |
    serve:
      port: 8080
      base_url: http://studio.localhost:8080/.auth/


    urls:
      error: http://studio.localhost:8080/.auth/error

    identities:
      cookie_name: ory_kratos_session
      tenants:
        tenant-a: Cool Company AS

    flows:
      login:
        flow_id_query_parameter: id
        csrf_token_parameter: csrf_token
        provider_parameter: provider
      tenant:
        flow_id_query_parameter: login_challenge
        flow_id_form_parameter: login_challenge
        flow_tenant_form_parameter: tenant
      consent:
        flow_id_query_parameter: consent_challenge

    clients:
      hydra:
        endpoints:
          admin: http://browser.system-auth.svc.cluster.local:4445/
      kratos:
        endpoints:
          public: http://localhost:4433/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system-auth
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      system: auth
      component: users
  template:
    metadata:
      labels:
        system: auth
        component: users
    spec:
      initContainers:
      - name: kratos-init
        image: oryd/kratos:v0.5.4
        args:
        - "--config"
        - "/etc/kratos/config/kratos.yaml"
        - "migrate"
        - "sql"
        - "-e"
        - "--yes"
        volumeMounts:
        - name: config
          mountPath: /etc/kratos/config
      containers:
      - name: kratos
        image: oryd/kratos:v0.5.4
        args:
        - "--config"
        - "/etc/kratos/config/kratos.yaml"
        - "serve"
        - "--dev"
        volumeMounts:
        - name: config
          mountPath: /etc/kratos/config
        ports:
        - name: kratos-public
          containerPort: 4433
        - name: kratos-admin
          containerPort: 4434
      - name: login
        image: dolittle/login:local
        args:
        - "--config"
        - "/etc/login/config/login.yaml"
        - "serve"
        ports:
        - name: login-public
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/login/config
      volumes:
      - name: config
        configMap:
          name: users

---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: system-auth
spec:
  selector:
    system: auth
    component: users
  ports:
  - port: 4433
    targetPort: kratos-public
    name: kratos-public
  - port: 8080
    targetPort: login-public
    name: login-public

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: system-auth
  name: users
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: studio.localhost
    http:
      paths:
      - path: /(\.auth/.*)
        backend:
          serviceName: users
          servicePort: login-public
      - path: /(\.auth/self-service/tenant/.*)
        backend:
          serviceName: users
          servicePort: login-public
      - path: /(\.auth/self-service/login/flows.*)
        backend:
          serviceName: users
          servicePort: login-public
      - path: /(\.auth/self-service/consent/.*)
        backend:
          serviceName: users
          servicePort: login-public
      - path: /\.auth/(self-service/.*)
        backend:
          serviceName: users
          servicePort: kratos-public

---
apiVersion: v1
kind: Service
metadata:
  namespace: system-auth
  name: kratos-admin-external
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    system: auth
    component: users
  ports:
  - port: 4434
    targetPort: kratos-admin
    name: kratos-admin
