serve:
  port: 80

  paths:
    initiate: /initiate
    complete: /callback
    logout: /logout

urls:
  error: http://localhost:80/error
  return:
    query_parameter: return_to
    default: http://localhost:80/return
    allowed:
      - http://localhost:80/return
    mode: strict

sessions:
  nonce_length: 80
  lifetime: 5m
  cookies:
    name: .dolittle.pascal.session
    secure: true
    samesite: lax
    path: /
  keys:
    - hash: KEY-USED-TO-SIGN-SESSION-COOKIES-SHOULD-BE-64-BYTES-LONG--------
      block: ENCRYPTION-KEY-SHOULD-BE-32-BYTS

openid:
  issuer: http://localhost:80
  client:
    id: client-id
    secret: client-secret
  scopes:
    - openid
  token_type: access_token
  redirect: http://localhost:80/callback

cookies:
  name: .dolittle.pascal.login
  secure: true
  samesite: lax
  path: /