---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: system-auth
  name: apiserver-proxy-config
data:
  oathkeeper.yaml: |
    serve:
      proxy:
        port: 4455
      api:
        port: 4456
      prometheus:
        port: 9000
    access_rules:
      repositories:
        - file:///etc/oathkeeper/config/rules.yaml

    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true

    mutators:
      bearer:
        enabled: true
        config:
          token_from:
            file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      
      header:
        enabled: true
        config:
          headers:
            Impersonate-User: '{{ print .Subject }}'

    authorizers:
      allow:
        enabled: true

    authenticators:
      anonymous:
        enabled: true

    log:
      level: debug
      format: text

  rules.yaml: |
    - id: apiserver
      upstream:
        url: https://kubernetes.default.svc
      match:
        methods: ["GET", "PATCH", "POST", "PUT", "DELETE"]
        url: http://localhost:4455/<.*>
      authenticators:
        - handler: anonymous
          config:
            subject: guest
      authorizer:
        handler: allow
      mutators:
        - handler: bearer
        - handler: header
      errors:
        - handler: json

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system-auth
  name: apiserver-proxy
  labels:
    system: auth

spec:
  selector:
    matchLabels:
      system: auth
      component: apiserver-proxy

  replicas: 1

  template:
    metadata:
      labels:
        system: auth
        component: apiserver-proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000" 
    spec:
      containers:
      - name: oathkeeper
        image: oryd/oathkeeper:dev
        args:
          - "--config"
          - "/etc/oathkeeper/config/oathkeeper.yaml"
          - "serve"
        env:
          - name: SSL_CERT_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        ports:
        - name: proxy
          containerPort: 4455
        - name: metrics
          containerPort: 9000
        volumeMounts:
        - name: config
          mountPath: /etc/oathkeeper/config
      volumes:
      - name: config
        configMap:
          name: apiserver-proxy-config
