serve:
  port: 8080

  paths:
    initiate: /initiate
    complete: /callback

urls:
  error: http://localhost:8080/error

sessions:
  nonce_length: 28
  cookie:
    name: "dolittle"
  keys:
    - hash: cvbnsdafh
      block: fdashglfds