name: Login

on:
  push:
    branches:
    - '**'

jobs:
  build-backend:
    name: "Backend : Build + Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Build
      working-directory: ./Source/Login/Backend
      run: go build .
    - name: Test
      working-directory: ./Source/Login/Backend
      run: go test -v ./...
  
  build-web:
    name: "Web : Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
    - name: Build
      working-directory: ./Source/Login/Web
      run: |
        yarn
        yarn build
