name: Pascal

on:
  push:
    branches:
    - '**'

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Build
      working-directory: ./Source/Pascal
      run: go build .
    - name: Test
      working-directory: ./Source/Pascal
      run: go test -v ./...
